monitoria/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('subsistema/', include('subsistema.urls')),  
    url(r'^$', auth_views.login, name='login'),    
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/login/'}, name='logout'),    
    url(r'^admin/', admin.site.urls),
]

subsistema/urls.py
from django.urls import path
from . import views

app_name = 'subsistema'
urlpatterns = [                  
    path('cadastrar/', views.aluno_cadastra, name='aluno_cadastra'),
    path('alunopedemonitor/', views.aluno_pede_monitor, name='aluno_pede_monitor'),
    path('home/', views.aluno_home, name='aluno_home'),
    path('registroatendimento/', views.aluno_registra_atendimento, name='aluno_registra_atendimento'),
    path('inscrever/', views.aluno_inscreve, name='aluno_inscreve'),
    path('falha/', views.falha, name='falha_'),
]

subsistema/models.py
from django.db import models
from django.contrib.auth.models import User


class Curso(models.Model):
    nomeCurso = models.CharField(max_length=50)

    def __str__(self):
        return self.nomeCurso


class Materia(models.Model):    
    curso = models.ForeignKey(Curso, on_delete=models.CASCADE)
    nomeMateria = models.CharField(max_length=50)

    def __str__(self):
        return self.nomeMateria


class Aluno(models.Model):
    semestreEntrada = models.CharField(max_length=5)
    curso = models.ForeignKey(Curso, on_delete=models.CASCADE)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.first_name+' '+self.user.last_name


class Professor(models.Model):
    estaNaComissao = models.CharField(max_length=1)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.first_name+' '+self.user.last_name


class VagaMonitor(models.Model):
    qtdInscritos = models.IntegerField(default=0)
    semestreEntrada = models.IntegerField()
    materias = models.ForeignKey(Materia, on_delete=models.CASCADE)
    candidatos = models.ForeignKey(Aluno, on_delete=models.CASCADE)
    professor = models.ForeignKey(Professor, on_delete=models.CASCADE)
    descricaoResultado = models.TextField()

    def __str__(self):
        return 'Vaga Monitoria:'+self.user.first_name+' '+self.user.last_name


class AlunoPedeMonitor(models.Model):
    comentario = models.TextField()
    materia = models.ForeignKey(Materia, on_delete=models.CASCADE)
    periodo = models.CharField(max_length=5)

    def __str__(self):
        return "Pedido:"+self.materia.nomeMateria


class EstadoMonitor(models.Model):
    nomeEstado = models.CharField(max_length=9)

    def __str__(self):
        return self.nomeEstado


class RegistroAtendimento(models.Model):
    dia = models.DateField('date published')
    horasMinistradas = models.IntegerField(default=0)
    linkListaPresenca = models.CharField(max_length=200)
    qtdAlunosPresentes = models.IntegerField(default=0)
    responsavel = models.ForeignKey(User, on_delete=models.CASCADE)


class Monitor(models.Model):
    horarioAtendimento = models.CharField(max_length=200)
    estado = models.ForeignKey(EstadoMonitor, on_delete=models.CASCADE)        
    atendimentos = models.ForeignKey(RegistroAtendimento, on_delete=models.CASCADE)

subsistema/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import AlunoPedeMonitor, RegistroAtendimento, VagaMonitor


class AlunoPedeMonitorForm(forms.ModelForm):
    class Meta:
        model = AlunoPedeMonitor
        fields = ('comentario', 'materia', 'periodo')


class AlunoCadastraForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, help_text='Inform a name.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')
    semestreEntrada = forms.CharField(max_length=5)
    
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', 'semestreEntrada')


class AlunoRegistraAtendimentoForm(forms.ModelForm):
    dia = forms.DateField(help_text='Required. Format: YYYY-MM-DD')

    class Meta:
        model = RegistroAtendimento
        fields = ('dia', 'horasMinistradas', 'linkListaPresenca', 'qtdAlunosPresentes')


class AlunoInscreveVagaForm(forms.ModelForm):
    class Meta:
        model = VagaMonitor
        fields = ('qtdInscritos', 'materias', 'professor')

subsistema/views.py
from django.shortcuts import render
from .forms import AlunoCadastraForm, AlunoRegistraAtendimentoForm, AlunoPedeMonitorForm, AlunoInscreveVagaForm
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.models import Group
from .models import Curso, RegistroAtendimento, Aluno
from django.urls import reverse
from django.http import HttpResponseRedirect


def is_authenticated(user):
    return user.is_authenticated


def is_aluno(user):    
    return user.groups.filter(name='aluno').exists()


def is_monitor(user):
    return user.groups.filter(name='monitor').exists()


def aluno_logado(user):
    return is_authenticated(user) and is_aluno(user)


def monitor_logado(user):
    return is_authenticated(user) and is_monitor(user)


def aluno_cadastra(request):
    if request.method == "POST":
        form = AlunoCadastraForm(request.POST)         
        if form.is_valid():
            user = form.save()
            user.refresh_from_db() 
            user.save()
            my_group = Group.objects.get(name='aluno') 
            my_group.user_set.add(user)
            Aluno(semestreEntrada=form.cleaned_data['semestreEntrada'], curso=form.cleaned_data['curso'],
                  user=user).save()
            return HttpResponseRedirect(reverse('subsistema:aluno_home'))
    else:
        form = AlunoCadastraForm()
    return render(request, 'subsistema/alunoCadastra.html', {'curso': Curso.objects.all(), 'form': form})


@user_passes_test(aluno_logado, login_url='/login/')
def aluno_home(request):
    return render(request, 'subsistema/alunoHome.html')


@user_passes_test(aluno_logado, login_url='/login/')
def aluno_pede_monitor(request):
    if request.method == "POST":
        form = AlunoPedeMonitorForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('subsistema:aluno_home'))
        else:
            return HttpResponseRedirect(reverse('subsistema:falha_'))
    else:
        form = AlunoPedeMonitorForm()
    return render(request, 'subsistema/AlunoPedeMonitor.html', {'form': form})


@user_passes_test(monitor_logado, login_url='/login/')
def aluno_registra_atendimento(request):
    if request.method == "POST":
        form = AlunoRegistraAtendimentoForm(request.POST)
        if form.is_valid():
            dia = form.cleaned_data['dia']
            horas_ministradas = form.cleaned_data['horasMinistradas']
            link_lista_presenca = form.cleaned_data['linkListaPresenca']
            qtd_alunos_presentes = form.cleaned_data['qtdAlunosPresentes']
            RegistroAtendimento(dia=dia, horasMinistradas=horas_ministradas, linkListaPresenca=link_lista_presenca
                                , qtdAlunosPresentes=qtd_alunos_presentes, responsavel=request.user).save()

            return HttpResponseRedirect(reverse('subsistema:aluno_home'))
    else:
        form = AlunoRegistraAtendimentoForm()

    return render(request, 'subsistema/alunoRegistraAtendimento.html', {'form': form})


@user_passes_test(aluno_logado, login_url='/login/')    
def aluno_inscreve(request):
    if request.method == "POST":
        form = AlunoInscreveVagaForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('subsistema:aluno_home'))
    else:
        form = AlunoInscreveVagaForm()

    return render(request, 'subsistema/alunoInscreve.html', {'form': form})


def falha(request):
    return render(request, 'subsistema/falha.html')

subsistema/templates/subsistema/AlunoPedeMonitor.html
{% extends 'subsistema/base.html' %}

{% block content %}
    <h1>Pedir novo monitor</h1>
    <form method="POST" class="post-form">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="submit" value="Salvar" class="save btn btn-default">
    </form>
    <a href="{% url 'subsistema:aluno_home' %}" class="btn btn-default">Voltar</a>
{% endblock %}

subsistema/templates/subsistema/alunoCadastra.html
{% extends 'subsistema/base.html' %}

{% block content %}
<form method="POST" class="post-form">
    {% csrf_token %}
    {{ form.as_p }}
    <select name="curso">
        {% for curso in curso %}
            {% ifequal curso.id selected_curso.id %}
                <option value="{{curso.key}}" selected="selected">curso {{curso.id}}: {{curso.nomeCurso}}</option>
            {% else %}
                <option value="{{curso.key}}">curso {{curso.id}}: {{curso.nomeCurso}}</option>
            {% endifequal %}
        {% endfor %}
    </select>
    <input type="submit" name="submit" value="Salvar" class="save btn btn-default">
</form>
<a href="{% url 'login' %}" class="btn btn-default">Voltar</a>    
{% endblock %}

subsistema/templates/subsistema/alunoHome.html
{% extends 'subsistema/base.html' %}

{% block content %}
    <a href="{% url 'subsistema:aluno_pede_monitor' %}" class="btn btn-default">Pedir Monitor</a>
    <a href="{% url 'subsistema:aluno_registra_atendimento' %}" class="btn btn-default">Registro atendimento</a>
    <a href="{% url 'subsistema:aluno_inscreve' %}" class="btn btn-default">Inscrever para monitor</a>
    
{% endblock %}


<!-- disabled  -->

subsistema/templates/subsistema/alunoInscreve.html
{% extends 'subsistema/base.html' %}

{% block content %}
    <h1>Vagas disponiveis</h1>
    <form method="POST" class="post-form">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="submit" value="Salvar" class="save btn btn-default">
    </form>
    <a href="{% url 'subsistema:aluno_home' %}" class="btn btn-default">Voltar</a>
{% endblock %}


<!-- disabled  -->

subsistema/templates/subsistema/alunoRegistraAtendimento.html
{% extends 'subsistema/base.html' %}

{% block content %}
    <h1>Novo Atendimento</h1>
    <form method="POST" class="post-form">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="submit" value="Salvar" class="save btn btn-default">
    </form>
    <a href="{% url 'subsistema:aluno_home' %}" class="btn btn-default">Voltar</a>
{% endblock %}

subsistema/templates/subsistema/base.html
{% load staticfiles %}
<html>
    <head>
        <title>Django </title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{% static 'css/subsistema.css' %}">
    </head>
    <body>
        <div class="page-header">
            <h1>Monitoria</h1>
            {% if user.is_authenticated %}   
                <p class="top-menu">Hello {{ user.username }} <small>(<a href="{% url 'logout' %}">Log out</a>)</small></p>            
                <a href="{% url 'subsistema:aluno_home' %}" class="top-menu">Inicio</span></a>
            {% else %}
                <a href="{% url 'login' %}" class="top-menu"><span class="glyphicon glyphicon-lock"></span></a>
            {% endif %}
            
        </div>
        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                {% block content %}
                {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

subsistema/templates/subsistema/falha.html
{% extends 'subsistema/base.html' %}

{% block content %}
    <h1>Falha</h1>
{% endblock %}